---
- name: Deploy Services (e.g., Ollama, WebUI, FastAPI)
  hosts: "{{ target_host | default('legalease') }}"
  vars:
    repo_name: "CPSC5830-Team1"
    repo_path: "/media/volume/LegalEase/Repos/{{ repo_name }}"
  tasks: 
  - name: Deploy Ollama and WebUI
    command: "./start.sh"
    args:
      chdir: "{{ repo_path }}/ollama"
    become: true
  
  - name: Deploy FastAPI server
    command: "./start.sh"
    args:
      chdir: "{{ repo_path }}/api"
    become: true
