---
- name: Initialize system
  hosts: "{{ target_host | default('legalease') }}"
  vars:
    ubuntu_version: "{{ ansible_distribution_version | replace('.', '') }}" # 24.04 -> 2404
  tasks:
    - name: Add repositories
      ansible.builtin.deb822_repository:
        name: "{{ item.name }}"
        suites: "{{ item.suites }}"
        uris: "{{ item.uris }}"
        signed_by: "{{ item.signed_by }}"
        components: "{{ item.components | default(omit) }}"
        types: deb
        state: present
      become: true
      loop:
        - name: nvidia-cuda
          suites: [/]
          uris: ["https://developer.download.nvidia.com/compute/cuda/repos/ubuntu{{ ubuntu_version }}/x86_64"]
          signed_by: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu{{ ubuntu_version }}/x86_64/3bf863cc.pub"
        - name: deadsnakes
          suites: ["{{ ansible_distribution_release }}"]
          uris: "https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu"
          signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF23C5A6CF475977595C89F51BA6932366A755776"
          components: [main]

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - cuda-toolkit
        - mosh
        - python3.11
        - python3.11-distutils
        - python3.11-venv
        - python3.11-dev
        - npm
      become: true

    - name: Install pnpm globally
      community.general.npm:
        name: pnpm
        global: yes
        state: present
      become: true
